name: surf-share
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=10.0.1=py36_0
  - python=3.6.6
  - uwsgi
  - libiconv
  - pip:
    - django==1.11
    - whitenoise==4.0
    - pytz==2018.5
