# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-14 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ims', '0002_ltiapp_ltitenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCartridgeShared',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ims.commoncartridge',),
        ),
    ]
