version: "3"

services:
  service:
    build: service
    volumes:
      - ./service:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_URL_PREFIX=/
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=lefkfqewfqw
