name: surf-share
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=10.0.1=py36_0
  - python=3.6.6
  - uwsgi
  - libiconv
  - lxml=4.2.5
  - beautifulsoup4=4.4.0
  - pip:
    - django==1.11
    - whitenoise==4.0
    - pytz==2018.5
    - django-bootstrap4==0.0.7
    - ipdb==0.11
